### PR TITLE
Create more examples of gaps with forced ventilation

### PR DESCRIPTION
**Pull request by christoph-maurer**
The examples shall explain the full range of gaps with forced ventilation.

### CODE REVIEW

**Comment by christoph-maurer** [comment]
edit: @simon-wacker has found the bug and solved it.

@simon-wacker I tried to add an absorptance to the shading analogous to the existing example DoubleOutsidePerforatedShade_SHGC.unit.cpp . However, I get the following error:
```
[----------] 5 tests from TestGapBetweenIrradiatedExteriorShadingAndGlassForcedVentilationOutsideAir
[ RUN      ] TestGapBetweenIrradiatedExteriorShadingAndGlassForcedVentilationOutsideAir.GapLayerSurfaceIRFlow
unknown file: Failure
C++ exception with description "map::at" thrown in SetUp().
[  FAILED  ] TestGapBetweenIrradiatedExteriorShadingAndGlassForcedVentilationOutsideAir.GapLayerSurfaceIRFlow (0 ms)
[ RUN      ] TestGapBetweenIrradiatedExteriorShadingAndGlassForcedVentilationOutsideAir.GainEnergy
unknown file: Failure
C++ exception with description "map::at" thrown in SetUp().
[  FAILED  ] TestGapBetweenIrradiatedExteriorShadingAndGlassForcedVentilationOutsideAir.GainEnergy (0 ms)
```
This error did not appear in [6c5799f](https://github.com/ise-bipv/Windows-CalcEngine/pull/5/commits/6c5799fd9994fbb1652bc5daa4d8747e01da0f8d) . In [6c5799f](https://github.com/ise-bipv/Windows-CalcEngine/pull/5/commits/6c5799fd9994fbb1652bc5daa4d8747e01da0f8d), the error was the result of changed input parameters like the sky temperature.

**Comment by christoph-maurer** [comment]
@simon-wacker How can I print the outlet temperature of the forced convection in a test?

**Comment by christoph-maurer** [comment]
I had a look at the results of the tests `GapLayer*` and I think they are plausible.

**Comment by christoph-maurer** [comment]
Does
```
auto gapThickness = 0.0127;
auto gapLayer = Tarcog::ISO15099::Layers::gap(gapThickness);
ASSERT_TRUE(gapLayer != nullptr);
```
represent a gap which is closed at the top and at the bottom?
How can gaps with openings at the top and the bottom be modelled?

**Comment by christoph-maurer** [comment]
@simon-wacker I tried to extend the tests for two glass panes with a shading in between, but I failed in [b78d795](https://github.com/ise-bipv/Windows-CalcEngine/pull/5/commits/b78d795463a740e9e8dd52049f945c98b86fad0f). How can I print the temperatures of the gaps correctly? The temperatures of the solid layers don't seem plausible. I expect the shading to have much higher temperatures than the outdoor and the indoor air.

**Comment by christoph-maurer** [comment]
@bbuenoun @simon-wacker The tests [GapBetweenIrradiatedGlassAndInteriorShadingZeroForcedVentilation.unit.cpp](https://github.com/ise-bipv/Windows-CalcEngine/blob/b78d795463a740e9e8dd52049f945c98b86fad0f/src/Tarcog/tst/units/GapBetweenIrradiatedGlassAndInteriorShadingZeroForcedVentilation.unit.cpp) and [GapBetweenIrradiatedGlassAndInteriorShadingNaturalConvection.unit.cpp](https://github.com/ise-bipv/Windows-CalcEngine/blob/b78d795463a740e9e8dd52049f945c98b86fad0f/src/Tarcog/tst/units/GapBetweenIrradiatedGlassAndInteriorShadingNaturalConvection.unit.cpp) should generate the same result, if the gap without forced convection is closed at the top and at the bottom which I assume.

**Comment by simonwacker** [comment]
> How can I print the outlet temperature of the forced convection in a test?

The [outlet temperature is a field of the ventilated gap's state](https://github.com/ise-bipv/Windows-CalcEngine/blob/b78d795463a740e9e8dd52049f945c98b86fad0f/src/Tarcog/src/IGUVentilatedGapLayer.hpp#L19) which [is private](https://github.com/ise-bipv/Windows-CalcEngine/blob/b78d795463a740e9e8dd52049f945c98b86fad0f/src/Tarcog/src/IGUVentilatedGapLayer.hpp#L89) and there is neither a getter for the state nor for the outlet temperature. To make the value accessible you could declare a getter for the state in https://github.com/ise-bipv/Windows-CalcEngine/blob/b78d795463a740e9e8dd52049f945c98b86fad0f/src/Tarcog/src/IGUVentilatedGapLayer.hpp#L35 and define it in the corresponding `cpp`-file. I could also do that for you.

**Comment by simonwacker** [comment]
> a gap which is closed at the top and at the bottom?
> How can gaps with openings at the top and the bottom be modeled?

As far as I understand it, gaps are neither open nor closed. However, the surrounding layers can be open or closed. They can for example be solid layers or shade layers with openings. See for example https://github.com/ise-bipv/Windows-CalcEngine/blob/b78d795463a740e9e8dd52049f945c98b86fad0f/src/Tarcog/tst/units/GapLayerInBetweenThermallyDrivenVentilation.unit.cpp#L48-L79 The open or closeness of the surrounding layers decide how the air flows within the gap if it is naturally ventilated.

**Comment by simonwacker** [comment]
> I tried to extend the tests for two glass panes with a shading in between, but I failed in [b78d795](https://github.com/ise-bipv/Windows-CalcEngine/pull/5/commits/b78d795463a740e9e8dd52049f945c98b86fad0f). How can I print the temperatures of the gaps correctly? The temperatures of the solid layers don't seem plausible. I expect the shading to have much higher temperatures than the outdoor and the indoor air.

At the end of the test set-up you need to call `m_TarcogSystem->solve();`. See for example https://github.com/ise-bipv/Windows-CalcEngine/blob/b78d795463a740e9e8dd52049f945c98b86fad0f/src/Tarcog/tst/units/GapLayerInBetweenForcedVentilation.unit.cpp#L76 Otherwise the system is as far as I understand in an initial state with default values. Temperatures and such are only resolved after calling the `solve` method.

**Comment by simonwacker** [comment]
@christoph-maurer When you make comments part of a review, then the comments are threads and we can have proper conversations about them. Review comments can also be marked as resolved. To add a review comment click on "Files changed" at the top and then on the green "Review Changes"-Button at the right. If your review comment belongs to code, then also under "File changed", go to the line, however over it, click on the blue plus sign that appears on the left, and add your comment. If it belongs not just to one line but to multiple lines you can also drag and drop the plus sign to select multiple lines for a comment.

**Review by christoph-maurer — COMMENTED** [review]
When the `windowHeight = 1;` and two layers have
```
 auto Atop = 0; 
 auto Abot = 0; 
 auto Aleft = 0; 
 auto Aright = 0; 
 auto Afront = 0; 
```
then I assume that the gas between two layers cannot leave the gap. This is what I meant by "closed" at the top and at the bottom. Or is there an option to let the air freely enter and leave the gap at the top and the bottom with
```
 auto Atop = 0; 
 auto Abot = 0; 
 auto Aleft = 0; 
 auto Aright = 0; 
 auto Afront = 0; 
```
?

**Review by christoph-maurer — COMMENTED** [review]
Thank you for your comments! Regarding https://github.com/ise-bipv/Windows-CalcEngine/pull/5#issuecomment-1408801124 , can you please add the getter? I think I couldn't do it well, but I would like to learn how you add it.

**Comment by simonwacker** [comment]
> Or is there an option to let the air freely enter and leave the gap at the top and the bottom with

I don't think so but I'm not sure. It depends on how the algorithms that compute airflow and such use those values. I have no deep understanding of the algorithms and the physics behind them, so I cannot really tell. @vidanovic Can you help us out here regarding https://github.com/ise-bipv/Windows-CalcEngine/pull/5#pullrequestreview-1277607856 which is a reply to https://github.com/ise-bipv/Windows-CalcEngine/pull/5#issuecomment-1408811537 which in turn is a reply to https://github.com/ise-bipv/Windows-CalcEngine/pull/5#issuecomment-1405042947?

**Comment by simonwacker** [comment]
@christoph-maurer I was wrong regarding standalone review comments: They are not the start of a thread (although [people really want this feature](https://github.com/community/community/discussions/8469) and [it's on the roadmap](https://github.com/github/roadmap/issues/552)). Threading only works with review comments for specific lines of code. So as a workaround for the future, if the comment does not belong to a specific line of code just pick an arbitrary one that most probably won't be touched by upcoming code changes.

**Comment by vidanovic** [comment]
@christoph-maurer For the forced ventilation, there is no need to define any of the openings. They are used in thermally driven ventilation to calculate the speed of the air. Since air is now entering with the forced speed entered by the user, there is no need for those openings. Actually, results should remain the same regardless of the entered opening. I would actually advice not to enter any openings for the forced ventilation.

**Comment by christoph-maurer** [comment]
> @christoph-maurer For the forced ventilation, there is no need to define any of the openings. They are used in thermally driven ventilation to calculate the speed of the air. Since air is now entering with the forced speed entered by the user, there is no need for those openings. Actually, results should remain the same regardless of the entered opening. I would actually advice not to enter any openings for the forced ventilation.

Thank you @vidanovic ! Is the following statement about natural convection correct? "When two layers have no openings, then the gap in between is always closed at the top and the bottom of the gap."

**Comment by vidanovic** [comment]
@christoph-maurer Yes, the gap is closed for the natural ventilation. However, please note that you can still create forced ventilation gap even with all those coefficients set to zero.

**Comment by christoph-maurer** [comment]
> @christoph-maurer Yes, the gap is closed for the natural ventilation. However, please note that you can still create forced ventilation gap even with all those coefficients set to zero.

Thank you @vidanovic ! Now it's clear to me.

**Pull request merged**
